CREATE TABLE [dbo].[DIM_COMMON_CUSTOMER] (
    [ORGANIZATIONLVL3ID]       INT NULL,
    [CUSTOMER_NO]     INT          NOT NULL,
    [CUSTOMER_CODE]   VARCHAR (50) NULL,
    [NAME]            VARCHAR (75) NULL,
    [CUSTOMER_TYPE]   VARCHAR (50) NULL,
    [CUSTOMER_STATUS] BIT          NULL,
    CONSTRAINT [PK_DIM_COMMON_CUSTOMER_1] PRIMARY KEY CLUSTERED ([CUSTOMER_NO] ASC)
);

