CREATE TABLE [dbo].[DIM_ACCOUNTING_CLASSIFICATION] (
    [ORGANIZATIONLVL3ID]      INT NOT NULL,
    [ACCOUNT_NO]     NVARCHAR (20) NOT NULL,
    [CLASSIFICATION] NVARCHAR (40) NULL,
    CONSTRAINT [PK_DIM_ACCOUNTING_CLASSIFICATION] PRIMARY KEY CLUSTERED ([ORGANIZATIONLVL3ID] ASC, [ACCOUNT_NO] ASC)
);

