CREATE TABLE [dbo].[DIM_MATERIAL_MATERIAL_ATTRIBUTES]
(
    [MATERIAL_ID] INT NOT NULL, 
    [MATERIAL_TYPE_ID] INT NULL, 
    [MATERIAL_FAMILY_ID] INT NULL, 
    [CUSTOMER_ID] INT NULL, 
    [CUSTOMER_NO_FOR_PURCHASING] VARCHAR(50) NULL, 
    [MINIMUM_ORDER_QUANTITY] DECIMAL(18, 6) NULL, 
    [LEAD_TIME] DECIMAL(18, 6) NULL, 
    [COMMODITY_CODE] VARCHAR(50) NULL, 
    [MINIMUM_DELIVERY_QUANTITY] DECIMAL(18, 6) NULL, 
    [PLANNING_GROUP_FOR_PURCHASING] VARCHAR(50) NULL, 
    [ESTIMATED_ANNUAL_USAGE] DECIMAL(18, 6) NULL, 
    [IS_CUSTOMER_CONTROLLED] VARCHAR(50) NULL, 
    [FREIGHT] DECIMAL(18, 3) NULL DEFAULT 0, 
    [LETTER_OF_AUTHORIZATION] VARCHAR(50) NULL DEFAULT '', 
    [CUSTOMER_PART_NO] VARCHAR(100) NULL DEFAULT '', 
    [COUNTRY_ID] VARCHAR(50) NULL DEFAULT '', 
    [HARMONIZED_TARIFF_CODE] VARCHAR(50) NULL DEFAULT '', 
    CONSTRAINT [PK_DIM_MATERIAL_MATERIAL_ATTRIBUTES] PRIMARY KEY ([MATERIAL_ID]) 
)
