CREATE TABLE [dbo].[DIM_COMMON_SITE] (
    [ORGANIZATIONLVL3ID] INT NOT NULL, 
    [SITE_CODE]          NVARCHAR (20) NOT NULL,
    [SITE]               NVARCHAR (50) NOT NULL,
    [SITE_SHORT_NAME]    NVARCHAR (10) NULL,
    [ORGANIZATIONLVL2ID]      INT NULL,
    [COUNTRY]            NVARCHAR (50) NULL,
    [STATE]              NVARCHAR (50) NULL,
    [PLEXUS_CUSTOMER_NO] INT           NULL,
    CONSTRAINT [PK_DIM_COMMON_SITE] PRIMARY KEY ([ORGANIZATIONLVL3ID], [SITE_CODE]) 
);

