CREATE TABLE [dbo].[DIM_COMMON_CURRENCY]
(
	[CURRENCY_ID] INT NOT NULL , 
    [CURRENCY_SYMBOL] NVARCHAR(4) NULL, 
    [CURRENCY_CODE] NVARCHAR(4) NOT NULL, 
    [DESCRIPTION] NVARCHAR(50) NULL, 
    [ACTIVE] BIT NULL, 
    PRIMARY KEY ([CURRENCY_CODE])
)
