CREATE TABLE [dbo].[DIM_COMMON_BUILDING] (
    [BUILDING_KEY]  INT           NOT NULL,
    [BUILDING_CODE] NVARCHAR (50) NULL,
    [ORGANIZATIONLVL3ID]          INT NULL,
    CONSTRAINT [PK_DIM_BUILDING] PRIMARY KEY CLUSTERED ([BUILDING_KEY] ASC)
);

