CREATE TABLE [dbo].[DIM_MATERIAL_OPERATION]
(
	[OPERATION_ID] INT NOT NULL  IDENTITY(1,1), 
    [OPERATION_CODE_UNIQUE] NVARCHAR(50) NOT NULL, 
    [OPERATION_CODE] NVARCHAR(50) NULL, 
    [INVENTORY_TYPE] NVARCHAR(50) NULL, 
    PRIMARY KEY ([OPERATION_CODE_UNIQUE])
)
