CREATE TABLE [dbo].[DIM_MATERIAL_MATERIAL_ATTRIBUTES]
(
    [MATERIAL_ID] INT NOT NULL, 
    [MATERIAL_TYPE_ID] INT NULL, 
    [MATERIAL_FAMILY_ID] INT NULL, 
    [CUSTOMER_ID] INT NULL, 
    [CUSTOMER_NO_FOR_PURCHASING] VARCHAR(50) NULL, 
    [MINIMUM_ORDER_QUANTITY] DECIMAL(18, 6) NULL, 
    [LEAD_TIME] DECIMAL(18, 6) NULL, 
    [COMMODITY_CODE] VARCHAR(50) NULL, 
    CONSTRAINT [PK_DIM_MATERIAL_MATERIAL_ATTRIBUTES] PRIMARY KEY ([MATERIAL_ID]) 
)
