CREATE TABLE [dbo].[DIM_ACCOUNTING_ACCOUNT] (
    [ORGANIZATIONLVL3ID]      INT NOT NULL,
    [ACCOUNT_NO]     NVARCHAR (20) NOT NULL,
    [ACCOUNT_NAME]   NVARCHAR (60) NULL,
    [BASE_NO]        NVARCHAR (10) NULL,
    [COST_CENTER_NO] NVARCHAR (10) NULL,
    [LOCATION_NO]    NVARCHAR (10) NULL,
    [CATEGORY_TYPE]  NVARCHAR (20) NULL,
    [CLASSIFICATION] NVARCHAR (40) NULL,
    CONSTRAINT [PK_DIM_ACCOUNTING_ACCOUNT_1] PRIMARY KEY CLUSTERED ([ORGANIZATIONLVL3ID] ASC, [ACCOUNT_NO] ASC)
);

