CREATE TABLE [dbo].[DIM_ACCOUNTING_ACCOUNT]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL,
    [ACCOUNT]            VARCHAR (50)    NOT NULL,
    [ACCOUNT_NAME]       VARCHAR (150)   NULL,
    [BASE_NO]            VARCHAR (50)    NULL,
    [COST_CENTER_NO]     VARCHAR (50)    NULL,
    [LOCATION_NO]        VARCHAR (50)    NULL,
    [CATEGORY_TYPE]      VARCHAR (50)    NULL,
    [CLASSIFICATION]     VARCHAR (50)    NULL, 
    [ACCOUNT_KEY] INT NULL, 
    CONSTRAINT [PK_DIM_ACCOUNTING_ACCOUNT] PRIMARY KEY ([ORGANIZATIONLVL3ID], [ACCOUNT]),
)
