CREATE TABLE [dbo].[DIM_COMMON_BUILDING] (
    [BUILDING_ID]  INT  NOT NULL IDENTITY(1,1),
    [BUILDING_CODE_UNIQUE] NVARCHAR (50) NOT NULL,
    [BUILDING_CODE] NVARCHAR (50) NULL,
    [PLANT_NO] INT NULL DEFAULT 1, 
    CONSTRAINT [PK_DIM_BUILDING] PRIMARY KEY CLUSTERED ([BUILDING_CODE_UNIQUE])
);

