CREATE TABLE [dbo].[DIM_COMMON_BUSINESS_UNIT] (
    [ORGANIZATIONLVL2ID] INT NOT NULL, 
    [BUSINESS_UNIT_SHORT_NAME] NVARCHAR (10) NOT NULL,
    [BUSINESS_UNIT]            NVARCHAR (50) NOT NULL,
    [ACTIVITY_NAME]            NVARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_BUSINESS_UNIT] PRIMARY KEY CLUSTERED ([ORGANIZATIONLVL2ID], [BUSINESS_UNIT_SHORT_NAME]),
    CONSTRAINT [FK_DIM_BUSINESS_UNIT_DIM_BUSINESS_UNIT] FOREIGN KEY ([ACTIVITY_NAME]) REFERENCES [dbo].[DIM_COMMON_ACTIVITY] ([ACTIVITY_NAME])
);

