CREATE TABLE [dbo].[DIM_COMMON_SUPPLIER]
(
	  [SUPPLIER_ID]     INT NOT NULL IDENTITY(1,1),
    [SUPPLIER_CODE_UNIQUE]   VARCHAR (50) NOT NULL,
    [SUPPLIER_CODE]   VARCHAR (50) NULL,
    [NAME]            VARCHAR (100) NULL,
    CONSTRAINT [PK_DIM_COMMON_SUPPLIER] PRIMARY KEY CLUSTERED ([SUPPLIER_CODE_UNIQUE])
)
