CREATE TABLE [dbo].[ODS_MATERIAL_COST_PRICE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NOT NULL, 
    [MATERIAL_STATUS] NVARCHAR(50) NULL, 
    [COST] DECIMAL(18, 6) NULL, 
    [COST_MODEL] NVARCHAR(50) NULL, 
    [COST_MASTER_PRICE] DECIMAL(18, 6) NULL, 
    [SALES_PO_PRICE] DECIMAL(18, 6) NULL,
    [SALES_PO_NO] NVARCHAR(50) NULL,  
    [SNAPSHOT_DATE] DATE NOT NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [MATERIAL_ID], [SNAPSHOT_DATE])
)
