CREATE TABLE [dbo].[ODS_MATERIAL_PRODUCTION]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [QUANTITY] DECIMAL(18, 6) NULL, 
    [TRANSACTION_DATE] DATETIME NULL, 
    [REPORT_DATE] DATE NOT NULL, 
    [REJECTED] BIT NULL, 
    [OPERATION_ID] INT NULL, 
    [INVENTORY_TYPE] VARCHAR(50) NULL, 
    [LOCATION_ID] INT NULL, 
    [BUILDING_ID] INT NULL, 
    [SERIAL_NO] VARCHAR(20) NOT NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [SERIAL_NO], [REPORT_DATE])
)
