CREATE TABLE [dbo].[ODS_MATERIAL_INVENTORY]
(	
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [TRNDATE] DATE NOT NULL, 
    [MATERIAL_ID] INT NOT NULL, 
    [BUILDING_ID] INT NULL, 
    [LOCATION] NVARCHAR(80) NOT NULL, 
    [MATERIAL_STATUS] NVARCHAR(50) NOT NULL, 
    [CONSIGMENT] BIT NULL, 
    [OPERATION_ID] INT NOT NULL, 
    [QUANTITY] DECIMAL NULL, 
    [UNIT_COST] DECIMAL NULL, 
    [EXT_COST] DECIMAL NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [TRNDATE], [MATERIAL_ID], [LOCATION], [MATERIAL_STATUS], [OPERATION_ID])
)
