CREATE TABLE [dbo].[ODS_MATERIAL_COST_PRICE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL PRIMARY KEY, 
    [MATERIAL_ID] INT NULL, 
    [COST] DECIMAL(18, 6) NULL, 
    [COST_MODEL] NVARCHAR(50) NULL, 
    [PO_PRICE] DECIMAL(18, 6) NULL,
    [PO_NO_PRICE] NVARCHAR(50) NULL,  
    [MASTER_PRICE] DECIMAL(18, 6) NULL, 
    [MATERIAL_STATUS] NVARCHAR(50) NULL
)
