CREATE TABLE [dbo].[ODS_MATERIAL_ADJUSMENT]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [ADJUSTMENT_KEY] INT NOT NULL, 
    [SERIAL_NO] VARCHAR(20) NULL, 
    [OPERATION_ID] INT NULL, 
    [BUILDING_ID] INT NULL, 
    [QUANTITY] DECIMAL(18, 6) NULL, 
    [ADJUSTMENT_DATE] DATETIME NULL, 
    [REPORT_DATE] DATE NULL, 
    [LOCATION_ID] INT NULL, 
    [ADJUSTMENT_REASON] NCHAR(10) NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [ADJUSTMENT_KEY])
)
