CREATE TABLE [dbo].[ODS_MATERIAL_SUPPLIER_BOND_PIPELINE]
(
    [SUPPLIER_ID] INT NOT NULL, 
    [ORGANIZATIONLVL3ID] INT NOT NULL, 
    [MATERIAL_ID] INT NOT NULL, 
    [Quantity] DECIMAL(18, 6) NOT NULL, 
    [Due_Date] DATE NOT NULL, 
    [TRNDATE] DATE NOT NULL, 
    CONSTRAINT [PK_ODS_MATERIAL_SUPPLIER_BOND_PIPELINE] PRIMARY KEY ([SUPPLIER_ID], [ORGANIZATIONLVL3ID], [MATERIAL_ID], [Due_Date], [TRNDATE])
)
