CREATE TABLE [dbo].[ODS_MATERIAL_SCRAP]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [SCRAP_ID] INT NOT NULL, 
    [MATERIAL_ID] INT NULL, 
    [REPORT_DATE] DATE NULL, 
    [TRANSACTION_DATE] DATETIME NULL, 
    [SCRAP_REASON] VARCHAR(150) NULL, 
    [UNIT_PRICE] DECIMAL NULL, 
    [SCRAP_QUANTITY] DECIMAL NULL, 
    [EXT_COST] DECIMAL NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [SCRAP_ID])
)
