CREATE TABLE [dbo].[ODS_ACCOUNTING_BALANCE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
	[BALANCE_KEY] INT NOT NULL , 
    [ACCOUNT] VARCHAR(50) NULL, 
    [PERIOD] VARCHAR(10) NOT NULL, 
    [DEBIT] DECIMAL(18, 6) NULL, 
    [CREDIT] DECIMAL(18, 6) NULL, 
    [BALANCE] DECIMAL(18, 6) NULL
)
