CREATE TABLE [dbo].[ODS_ACCOUNTING_BALANCE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
	[BALANCE_KEY] INT NOT NULL , 
    [ACCOUNT] VARCHAR(50) NOT NULL, 
    [PERIOD] VARCHAR(10) NOT NULL, 
    [DEBIT] DECIMAL(18, 6) NULL, 
    [CREDIT] DECIMAL(18, 6) NULL, 
    [BALANCE] DECIMAL(18, 6) NULL, 
    CONSTRAINT [PK_ODS_ACCOUNTING_BALANCE] PRIMARY KEY ([ORGANIZATIONLVL3ID], [ACCOUNT], [PERIOD])
)
