CREATE TABLE [dbo].[ODS_MATERIAL_PRODUCTION]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [QUANTITY] DECIMAL(18, 6) NULL, 
    [TRANSACTION_DATE] DATETIME NULL, 
    [REPORT_DATE] DATE NOT NULL, 
    [REJECTED] BIT NULL, 
    [OPERATION_ID] INT NOT NULL, 
    [INVENTORY_TYPE] VARCHAR(50) NULL, 
    [LOCATION_ID] INT NULL, 
    [BUILDING_ID] INT NULL, 
    [SERIAL_NO] VARCHAR(20) NOT NULL, 
    [SALE_UNIT_PRICE] DECIMAL(18, 6) NULL, 
    CONSTRAINT [PK_ODS_MATERIAL_PRODUCTION] PRIMARY KEY ([ORGANIZATIONLVL3ID], [OPERATION_ID], [SERIAL_NO]) 
)
