CREATE TABLE [dbo].[ODS_SALES_RELEASE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [RELEASE_NO] VARCHAR(50) NULL, 
    [RELEASE_ID] INT NOT NULL, 
    [RELEASE_STATUS] VARCHAR(50) NULL, 
    [PO] VARCHAR(50) NULL, 
    [PO_LINE_KEY] INT NOT NULL, 
    [QUANTITY] DECIMAL(18, 6) NULL, 
    [PRELIMINARY_DUE_DATE] DATE NULL, 
    [SNAPSHOT_DATE] DATE NOT NULL, 
    [DUE_DATE] DATE NULL, 
    [RELEASE_SOURCE] VARCHAR(50) NULL, 
    [RELEASE_TYPE] VARCHAR(50) NULL, 
    [FIRM] BIT NULL, 
    [PLANNING] BIT NULL, 
    [FORECAST_INCLUDE] BIT NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [RELEASE_ID], [PO_LINE_KEY], [SNAPSHOT_DATE])
)
