CREATE TABLE [dbo].[ODS_ACCOUNTING_BUDGET]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL PRIMARY KEY, 
    [BUDGET_VERSION_KEY] INT NULL, 
    [BUDGET_VERSION_NAME] VARCHAR(50) NULL, 
    [ACCOUNT_KEY] INT NULL, 
    [ACCOUNT] VARCHAR(50) NULL, 
    [PERIOD] VARCHAR(50) NULL, 
    [BUDGET] NCHAR(10) NULL
)
