CREATE TABLE [dbo].[ODS_HUMAN_RESOURCES_PAID_HOURS]
(
	[EMPLOYEEID] INT NOT NULL , 
    [NAME] NVARCHAR(50) NOT NULL, 
    [ORDINARY_HOURS] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
    [OVERTIME] DECIMAL(18, 6) NOT NULL DEFAULT 0, 
    [SHIFT] NVARCHAR(10) NOT NULL, 
    [CLASSIFICATION] CHAR NOT NULL, 
    [PLANT] NVARCHAR(10) NOT NULL, 
    [JOB_POSITION] NVARCHAR(50) NOT NULL, 
    [AREA] NVARCHAR(30) NOT NULL, 
    [APU] NVARCHAR(50) NOT NULL, 
    [TRNDATE] DATE NOT NULL
)
