CREATE TABLE [dbo].[ODS_MATERIAL_BOM]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NOT NULL, 
    [COMPONENT_MATERIAL_ID] INT NOT NULL, 
    [BOM_LEVEL] INT NULL, 
    [BOM_QUANTITY] DECIMAL(18, 6) NULL, 
    [BOM_KEY] INT NOT NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [COMPONENT_MATERIAL_ID], [MATERIAL_ID], [BOM_KEY])
)
