CREATE TABLE [dbo].[ODS_HUMAN_RESOURCES_ACCIDENTS]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [INJURY_NO] INT NOT NULL, 
    [INJURY_DATE] DATE NULL, 
    [EMPLOYEE_NO] INT NULL, 
    [NAME] NVARCHAR(100) NULL, 
    [INJURY_LOCATION] NVARCHAR(50) NULL, 
    [INJURY_TYPE] NVARCHAR(50) NULL, 
    [ATTENTION_PLACE] NVARCHAR(50) NULL, 
    [LOST_WORK_DAYS] INT NULL, 
    [NOTE] NVARCHAR(MAX) NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [INJURY_NO])
)
