CREATE TABLE [dbo].[ODS_ACCOUNTING_BUDGET]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [BUDGET_VERSION_KEY] INT NOT NULL, 
    [BUDGET_VERSION_NAME] VARCHAR(50) NULL, 
    [ACCOUNT_KEY] INT NOT NULL, 
    [ACCOUNT] VARCHAR(50) NULL, 
    [PERIOD] VARCHAR(50) NOT NULL, 
    [BUDGET] NCHAR(10) NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [BUDGET_VERSION_KEY], [ACCOUNT_KEY], [PERIOD])
)
