CREATE TABLE [dbo].[DIM_CALENDAR]
(
	[CALENDAR_DATE] DATE NOT NULL PRIMARY KEY, 
    [YEAR] INT NULL, 
    [MONTH] INT NULL, 
    [DAY] INT NULL, 
    [DAY_OF_WEEK] INT NULL, 
    [WEEK_OF_YEAR] INT NULL, 
    [IS_WEEKEND] BIT NULL, 
    [IS_HOLIDAY] BIT NULL
)
