CREATE TABLE [dbo].[DIM_COMMON_ORGANIZATION_LEVEL2_BUSINESS_UNIT] (
    [ORGANIZATIONLVL2ID] INT NOT NULL, 
    [BUSINESS_UNIT_SHORT_NAME] NVARCHAR (10) NOT NULL,
    [BUSINESS_UNIT]            NVARCHAR (50) NOT NULL,
    [ACTIVITY_NAME]            NVARCHAR (50) NULL,
    [ORGANIZATIONLVL1ID] INT NULL, 
    CONSTRAINT [PK_DIM_BUSINESS_UNIT] PRIMARY KEY CLUSTERED ([ORGANIZATIONLVL2ID], [BUSINESS_UNIT_SHORT_NAME])
);

