CREATE TABLE [dbo].[DIM_MATERIAL_MATERIAL]
(	
    [MATERIAL_ID] INT NOT NULL IDENTITY(1,1), 
    [MATERIAL_NO_UNIQUE] VARCHAR(50) NOT NULL, 
    [MATERIAL_NO] VARCHAR(50) NULL, 
    [MATERIAL_REVISION] NVARCHAR(10) NULL,
    [DESCRIPTION] VARCHAR(250) NULL, 
    [ACTIVE] BIT NULL,  
    [ORGANIZATIONLVL3ID] INT NULL, 
    PRIMARY KEY ([MATERIAL_NO_UNIQUE])
)
