CREATE TABLE [dbo].[DIM_COMMON_COUNTRY]
(
	[COUNTRY_ID] INT NOT NULL IDENTITY(1,1), 
    [COUNTRY] NVARCHAR(50) NOT NULL, 
    [COUNTRY_CODE] VARCHAR(50) NULL, 
    [CURRENCY_ID] INT NULL, 
    [ACTIVE] BIT NULL, 
    PRIMARY KEY ([COUNTRY])
)
