CREATE TABLE [dbo].[DIM_COMMON_CUSTOMER] (
    [CUSTOMER_ID]     INT NOT NULL IDENTITY(1,1),
    [CUSTOMER_CODE_UNIQUE]   VARCHAR (50) NOT NULL,
    [CUSTOMER_CODE]   VARCHAR (50) NULL,
    [NAME]            VARCHAR (75) NULL,
    CONSTRAINT [PK_DIM_COMMON_CUSTOMER_1] PRIMARY KEY CLUSTERED ([CUSTOMER_CODE_UNIQUE])
);

