CREATE TABLE [dbo].[DIM_COMMON_ORGANIZATION_LEVEL1_ACTIVITY] (
    [ORGANIZATIONLVL1ID] INT NOT NULL, 
    [ACTIVITY_SHORT_NAME] NVARCHAR (10) NOT NULL,
    [ACTIVITY_NAME]       NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ACTIVITY] PRIMARY KEY CLUSTERED ([ORGANIZATIONLVL1ID], [ACTIVITY_SHORT_NAME])
);

