CREATE TABLE [dbo].[DIM_COMMON_LOCATION]
(
	[LOCATION_ID] INT NOT NULL IDENTITY(1,1), 
    [LOCATION_UNIQUE] NVARCHAR(50) NOT NULL, 
    [LOCATION] NVARCHAR(50) NULL, 
    [BUILDING_ID] INT NULL, 
    PRIMARY KEY ([LOCATION_UNIQUE])
)
