CREATE TABLE [dbo].[DIM_COMMON_COUNTRY_STATE]
(
    [STATE_ID] INT NOT NULL IDENTITY(1,1), 
	[STATE_CODE] NVARCHAR(50) NOT NULL , 
    [STATE] NVARCHAR(50) NULL, 
    [COUNTRY_ID] INT NOT NULL, 
    PRIMARY KEY ([COUNTRY_ID], [STATE_CODE])
)
