CREATE TABLE [dbo].[DIM_COMMON_MANUFACTURER]
(
	[MANUFACTURER_NO] INT NOT NULL IDENTITY(1,1), 
    [MANUFACTURER_CODE_UNIQUE] VARCHAR(150) NOT NULL, 
    [MANUFACTURER_CODE] VARCHAR(150) NULL, 
    [MANUFACTURER_NAME] VARCHAR(150) NULL, 
    CONSTRAINT [PK_DIM_COMMON_MANUFACTURER] PRIMARY KEY ([MANUFACTURER_CODE_UNIQUE])
)
