CREATE TABLE [dbo].[ODS_MATERIAL_MANUFACTURER_PART_NO]
(
	[MATERIAL_ID] INT NOT NULL , 
    [MANUFACTURER_PART_NO] VARCHAR(150) NULL, 
    [MANUFACTURER_PART_STATUS] VARCHAR(50) NULL, 
    [ACTIVE] BIT NULL, 
    [SUPPLIER_ID] INT NOT NULL, 
    [MANUFACTURER_ID] INT NOT NULL, 
    [PRIMARY_SUPPLIER] BIT NULL, 
    [MANUFACTURER_PART_KEY_UNIQUE] VARCHAR(50) NOT NULL, 
    PRIMARY KEY ([MANUFACTURER_PART_KEY_UNIQUE], [SUPPLIER_ID], [MANUFACTURER_ID], [MATERIAL_ID])
)
