CREATE TABLE [dbo].[ODS_PURCHASE_APPROVED_SUPPLIER_PRICE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [APPROVED_SUPPLIER_PRICE_KEY] INT NOT NULL, 
    [PRICE] DECIMAL(18, 6) NULL, 
    [EFFECTIVE_DATE] DATE NULL, 
    [EXPIRATION_DATE] DATE NULL, 
    [CURRENCY_CODE] VARCHAR(50) NULL, 
    [SUPPLIER_ID] INT NULL, 
    [ESTIMATED_PRICE] BIT NULL, 
    [BREAKPOINT] INT NULL, 
    [ROW_NO] INT NULL, 
    [OPERATION_ID] INT NULL, 
    [SNAPSHOT_DATE] DATE NOT NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [APPROVED_SUPPLIER_PRICE_KEY], [SNAPSHOT_DATE])
)
