CREATE TABLE [dbo].[ODS_MATERIAL_COST_PRICE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NOT NULL, 
    [MATERIAL_STATUS] NVARCHAR(50) NULL, 
    [COST] DECIMAL(18, 6) NULL DEFAULT 0, 
    [COST_MODEL] NVARCHAR(50) NULL DEFAULT '', 
    [COST_MASTER_PRICE] DECIMAL(18, 6) NULL DEFAULT 0, 
    [SALES_PO_PRICE] DECIMAL(18, 6) NULL DEFAULT 0,
    [SALES_PO_NO] NVARCHAR(50) NULL DEFAULT '',  
    [SNAPSHOT_DATE] DATE NOT NULL, 
    [COST_PO] DECIMAL(18, 6) NULL DEFAULT 0, 
    [COST_PO_NO] NVARCHAR(50) NULL DEFAULT '', 
    [STANDART_COST] DECIMAL(18, 6) NULL DEFAULT 0, 
    [STANDART_COST_MODEL] NVARCHAR(50) NULL DEFAULT '', 
    [CUSTOMER_COST] DECIMAL(18, 6) NULL DEFAULT 0, 
    [CUSTOMER_COST_MODEL] NVARCHAR(50) NULL DEFAULT '', 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [MATERIAL_ID], [SNAPSHOT_DATE])
)
