CREATE TABLE [dbo].[ODS_PURCHASE_RELEASE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [RELEASE_NO] INT NOT NULL, 
    [RELEASE_STATUS] VARCHAR(20) NULL, 
    [INCLUDE_IN_MRP] SMALLINT NULL, 
    [PO] VARCHAR(50) NULL, 
    [PO_LINE_KEY] INT NOT NULL, 
    [QUANTITY] DECIMAL(18, 6) NULL, 
    [PRELIMINARY_DUE_DATE] DATE NULL, 
    [DUE_DATE] DATE NULL, 
    [SNAPSHOT_DATE] DATE NOT NULL, 
    [LINE_ITEM_STATUS] VARCHAR(20) NULL, 
    [RELEASE_LINE_NO] INT NULL, 
    [LINE_ITEM_NO] INT NULL, 
    [MASTER_UNIT_PRICE] BIT NULL, 
    [LINE_PRICE] DECIMAL(18, 6) NULL, 
    [SUPPLIER_PRICE] DECIMAL(18, 6) NULL, 
    [BLANKET_QUANTITY] NCHAR(10) NULL, 
    [OPERATION_ID] INT NULL, 
    [MANUFACTURER_NAME] VARCHAR(150) NULL, 
    [MANUFACTURER_PART_NO] VARCHAR(100) NULL, 
    [PO_TYPE] VARCHAR(50) NULL, 
    [BLANKET_ORDER] SMALLINT NULL, 
    [SUPPLIER_ID] INT NULL, 
    [PO_DATE] DATE NULL, 
    [CONSIGMENT] BIT NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [RELEASE_NO], [PO_LINE_KEY], [SNAPSHOT_DATE])
)

GO
CREATE NONCLUSTERED INDEX [idx_SNAPSHOT_RELEASESTATUS_i_MATERIALID_QUANTITY] ON [dbo].[ODS_PURCHASE_RELEASE]
(
	[SNAPSHOT_DATE] ASC,
	[RELEASE_STATUS] ASC
)
INCLUDE([MATERIAL_ID],[QUANTITY]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO