CREATE TABLE [dbo].[ODS_PRODUCTION_OEE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [BUILDING_ID] INT NOT NULL, 
    [STATIONID] INT NOT NULL, 
    [AREA] NVARCHAR(50) NULL, 
    [WORKCENTER] NVARCHAR(50) NULL, 
    [LOCATION_ID] INT NULL, 
    [REPORT_DATE] DATE NOT NULL, 
    [HOUR] INT NOT NULL, 
    [SHIFT] INT NULL, 
    [TRNDATE] DATE NOT NULL, 
    [OPERATIONAL_MINUTES] DECIMAL(18, 6) NULL, 
    [PROGRAMMED_DOWNTIME] DECIMAL(18, 6) NULL, 
    [AVAILABLE_MINUTES] DECIMAL(18, 6) NULL, 
    [EFFICENCY_MINUTES] DECIMAL(18, 6) NULL, 
    [QUALITY_MINUTES] DECIMAL NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [REPORT_DATE], [STATIONID], [BUILDING_ID], [HOUR], [TRNDATE])
)
