CREATE TABLE [dbo].[ODS_MATERIAL_MRP]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [DUE_DATE] DATE NULL, 
    [QUANTITY] DECIMAL(18, 6) NULL, 
    [MRP_KEY] BIGINT NOT NULL, 
    [ADD_DATE] DATE NOT NULL, 
    [OPERATION_ID] INT NULL, 
    [RELEASE_ID] INT NULL, 
    [Initial_Quantity] DECIMAL(18, 6) NULL, 
    [Ending_Quantity] DECIMAL(18, 6) NULL, 
    [TYPE] VARCHAR(50) NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [MRP_KEY], [ADD_DATE])
)
