CREATE TABLE [dbo].[ODS_SALES_RELEASE_PROJECTION]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [RELEASE_ID] INT NOT NULL, 
    [PO_LINE_KEY] INT NOT NULL, 
    [DUE_DATE] DATE NULL, 
    [QUANTITY] DECIMAL(18, 6) NULL, 
    [QUANTITY_ARBITRATION] DECIMAL(18, 6) NULL, 
    [QUANTITY_ALLOCATED] DECIMAL(18, 6) NULL, 
    [SNAPSHOT_DATE] DATE NOT NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [RELEASE_ID], [PO_LINE_KEY], [SNAPSHOT_DATE])
)
