CREATE TABLE [dbo].[ODS_MATERIAL_SUPPLIER_BOND_PROXIMITY]
(
    [ORGANIZATIONLVL3ID] INT NOT NULL, 
    [MATERIAL_ID] INT NOT NULL, 
    [Type] INT NOT NULL, 
    [Quantity] DECIMAL(18, 6) NOT NULL, 
    [Due_Date] DATE NOT NULL, 
    [Flg_Supplier_Data] BIT NOT NULL, 
    [SUPPLIER_ID] INT NOT NULL, 
    [Flg_Forecast] BIT NOT NULL, 
    [TRNDATE] DATE NOT NULL, 
    CONSTRAINT [PK_ODS_MATERIAL_SUPPLIER_BOND_PROXIMITY] PRIMARY KEY ([ORGANIZATIONLVL3ID], [MATERIAL_ID], [Due_Date], [TRNDATE], [SUPPLIER_ID]) 
)
