CREATE TABLE [dbo].[ODS_SALES_RELEASE]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [RELEASE_NO] VARCHAR(50) NULL, 
    [RELEASE_ID] INT NOT NULL, 
    [RELEASE_STATUS] VARCHAR(50) NULL, 
    [PO] VARCHAR(50) NULL, 
    [PO_LINE_KEY] INT NOT NULL, 
    [QUANTITY] DECIMAL(18, 6) NULL, 
    [PRELIMINARY_DUE_DATE] DATE NULL, 
    [SNAPSHOT_DATE] DATE NOT NULL, 
    [DUE_DATE] DATE NULL, 
    [RELEASE_SOURCE] VARCHAR(50) NULL, 
    [RELEASE_TYPE] VARCHAR(50) NULL, 
    [FIRM] BIT NULL, 
    [PLANNING] BIT NULL, 
    [FORECAST_INCLUDE] BIT NULL, 
    [UNIT_PRICE] DECIMAL(18, 6) NULL, 
    [UNIT_COST] DECIMAL(18, 6) NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [RELEASE_ID], [PO_LINE_KEY], [SNAPSHOT_DATE])
)

GO
CREATE NONCLUSTERED INDEX [idx_SNAPSHOTDATE_DUEDATE_i_MATERIALID_QUANTITY] ON [dbo].[ODS_SALES_RELEASE]
(
	[SNAPSHOT_DATE] ASC,
	[DUE_DATE] ASC
)
INCLUDE([MATERIAL_ID],[QUANTITY]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO