CREATE TABLE [dbo].[ODS_SALES_DELIVERY]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [CUSTOMER_ID] INT NULL, 
    [PO_NO] VARCHAR(50) NULL, 
    [PO_Key] INT NULL, 
    [RELEASE_ID] INT NULL, 
    [QUANTITY] DECIMAL(18, 3) NULL, 
    [SHIPPING_DATE] DATE NULL, 
    [THEORICAL_DELIVERY_DATE] DATE NULL, 
    [PO_LINE_KEY] INT NOT NULL, 
    [CUSTOMER_DELIVERY_NUMBER] INT NOT NULL, 
    [DELIVERY_CREATION_DATE] DATE NULL, 
    [DELIVERY_MODIFICATION_DATE] DATE NULL, 
    PRIMARY KEY ([PO_LINE_KEY], [CUSTOMER_DELIVERY_NUMBER])
)
