CREATE TABLE [dbo].[ODS_SALES_RETURN]
(
	[ORGANIZATIONLVL3ID] INT NOT NULL , 
    [MATERIAL_ID] INT NULL, 
    [RETURN_NO] INT NOT NULL, 
    [DESCRIPTION] VARCHAR(250) NULL, 
    [TRANSACTION_DATE] DATETIME NULL, 
    [REPORT_DATE] DATE NULL, 
    [RETURN_REASON] VARCHAR(50) NULL, 
    [CATEGORY] VARCHAR(50) NULL, 
    [RETURN_ID] INT NULL, 
    [REPORTED_QUANTITY] DECIMAL(18, 6) NULL, 
    [RETURNED_QUANTITY] DECIMAL(18, 6) NULL, 
    [DEFECTIVE_QUANTITY] DECIMAL(18, 6) NULL, 
    [INCLUDE_IN_PPM] DECIMAL(18, 6) NULL, 
    [CREDIT_QUANTITY] DECIMAL(18, 6) NULL, 
    PRIMARY KEY ([ORGANIZATIONLVL3ID], [RETURN_NO])
)
