ALTER ROLE [db_datareader] ADD MEMBER [PROD_DWH_USER];
GO

ALTER ROLE [db_datawriter] ADD MEMBER [PROD_DWH_USER];
GO

ALTER ROLE [db_datareader] ADD MEMBER [REPORT_USER];
GO

ALTER ROLE [db_datawriter] ADD MEMBER [REPORT_USER];
GO

ALTER SERVER ROLE  [dbcreator]  ADD MEMBER [REPORT_USER];  
GO